apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hami-dra-monitor
  namespace: hami-system
  labels:
    app.kubernetes.io/component: monitor
    app.kubernetes.io/instance: hami
    app.kubernetes.io/name: hami
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: monitor
      app.kubernetes.io/instance: hami
      app.kubernetes.io/name: hami
  namespaceSelector:
    matchNames:
      - hami-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
