apiVersion: v1
kind: Pod
metadata:
  name: test-cuda-alloc
  namespace: test-dra
spec:
  schedulerName: volcano
  restartPolicy: Never
  containers:
  - name: ctr
    image: loihoangthanh1411/cuda-alloc-test:v1
    command: ["/usr/local/bin/alloc"]
  resourceClaims:
  - name: gpu
    resourceClaimName: single-gpu-0
